# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'time-planner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for time-planner

  target 'time-plannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'time-plannerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
